config/routes.rb
Rails.application.routes.draw do
  root 'notebook#index'
  resources :notebook
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notebook.rb
class Notebook < ApplicationRecord
end

app/models/pc.rb
class Pc < ApplicationRecord
end

app/models/pk.rb
class Pk < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notebook_controller.rb
class NotebookController < ApplicationController

  def index
    @notebooks = Notebook.all
  end

  def new
    @notebook = Notebook.new
  end

  def create
    @notebook = Notebook.new(notebook_params)
    if@notebook.save
      redirect_to '/', notice: '已成功新增筆記本！'
    else
      render :new
    end
  end

  def edit
    @notebook = Notebook.find_by(id: params[:id])
  end

  def update
    @notebook = Notebook.find_by(id: params[:id])
    if@notebook.update(notebook_params)
      redirect_to notebook_path, notice: '已成功更新筆記本！'
    else
      render :edit
    end
  end 

  def destroy
    @notebook = Notebook.find_by(id: params[:id])
    @notebook.destroy if @notebook
    redirect_to notebook_path, notice: '已成功刪除筆記本！'
  end

  private
  def notebook_params
    params.require(:notebook).permit(:title, :author)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebook_helper.rb
module NotebookHelper
end

app/views/layouts/abc.html.erb
<h1>xxx</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xcard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notebook/edit.html.erb
<h1>編輯筆記本</h1>

<%= link_to '回筆記本列表', notebook_index_path	 %>

<%= form_for(@notebook, url: new_notebook_path) do |form| %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :author %>
  <%= form.text_field :author %>
</div>


  <%= form.submit '編輯筆記本'%>
<% end %>

app/views/notebook/index.html.erb
<h1>筆記本列表</h1>

<%= link_to '新增筆記本', new_notebook_path %>

<hr>


<table>
  
    <thead>
      <tr>
        <td>名稱</td>
        <td>作者</td>
        <td>編輯</td>
        <td>刪除</td>
      </tr>
    </thead>

    <tbody>
      <% @notebooks.each do |notebook| %>
        <tr>
          <td><%= notebook.title %></td>
          <td><%= notebook.author %></td>
          <td><%= link_to '編輯筆記本', edit_notebook_path(notebook.id) %></td>
          <td><%= link_to '刪除筆記本', notebook_path(notebook), method: 'delete', data: {confirm: '確定要刪除嗎？' }%></td>
        </tr>
      <% end %>
    </tbody>


</table>

app/views/notebook/new.html.erb
<h1>新增筆記本</h1>

<%= link_to '回筆記本列表', notebook_index_path	 %>

<%= form_for(@notebook, url: notebook_index_path) do |form| %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :author %>
  <%= form.text_field :author %>
</div>


  <%= form.submit '新增筆記本'%>
<% end %>